### ISSUE TITLE
Hi,I ran this code on cpu and continuously got nan 

### ISSUE THREAD

**Issue by euphy233** [geifmany/cifar-vgg#7] opened 2018-11-22 05:28 UTC
Here's what I got. I wonder if I did anything wrong or should I change any paras?
Epoch 8/250
 - 2994s - loss: nan - acc: 0.0999 - val_loss: nan - val_acc: 0.1000
Epoch 9/250
 - 2870s - loss: nan - acc: 0.0995 - val_loss: nan - val_acc: 0.1000
Epoch 10/250
 - 3146s - loss: nan - acc: 0.1007 - val_loss: nan - val_acc: 0.1000
Epoch 11/250
 - 2894s - loss: nan - acc: 0.0996 - val_loss: nan - val_acc: 0.1000

**Comment by geifmany** [comment] 2018-11-22 10:47
Change the learning rage go 0.01
Duplicate of #1

**Closed as completed** 2018-11-22 10:47 UTC
